# Generated by Django 5.2.6 on 2025-09-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='capacity',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='session',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop'),
        ),
    ]
