# Generated by Django 5.2.6 on 2025-09-10 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_session_capacity_alter_session_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workshops.workshop'),
        ),
    ]
