# Generated by Django 5.0.14 on 2025-09-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='on-site', max_length=40)),
            ],
        ),
    ]
